/// <reference types="vitest/config" />
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { VitePWA } from 'vite-plugin-pwa';

export default defineConfig({
  plugins: [
    react(),
    VitePWA({
      // 'prompt' instead of 'autoUpdate' so the service worker doesn't
      // silently reload the page when a new deploy is detected — that
      // would blow away React state mid-onboarding (e.g., the user is on
      // the reveal-mnemonics screen, switches to a password manager to
      // copy the phrase, comes back to the wallet, and the page has
      // reloaded with fresh state and DIFFERENT mnemonics). With 'prompt'
      // we get update events that components/ui/UpdateBanner.tsx
      // surfaces as a tap-to-apply prompt. Onboarding state is preserved
      // across the reload via PersistedCreateFlowState in CreateWallet.tsx,
      // so the original mnemonics-clobber concern is now addressed even
      // if a user taps Update mid-flow.
      registerType: 'prompt',
      // The React hook (useRegisterSW from virtual:pwa-register/react)
      // owns SW registration — it's what produces the needRefresh signal
      // that UpdateBanner renders against. Disabling auto-inject avoids a
      // duplicate registration via the inlined registerSW.js script that
      // vite-plugin-pwa would otherwise emit into index.html.
      injectRegister: false,
      // Precache these alongside the manifest's icons so they're available
      // offline once installed. The icon set is generated by
      // scripts/generate-icons.mjs from public/brand/icon-color.svg.
      includeAssets: [
        'apple-touch-icon.png',
        'icons/icon.svg',
        'icons/favicon-16.png',
        'icons/favicon-32.png',
      ],
      manifest: {
        name: 'xx Wallet',
        short_name: 'xx Wallet',
        description: 'Mobile wallet for the xx network',
        // ink-950 — the actual app background. Matches the in-app
        // loading state so the launch transition stays seamless.
        theme_color: '#0a0a0a',
        background_color: '#0a0a0a',
        display: 'standalone',
        orientation: 'portrait',
        start_url: '/',
        lang: 'en',
        dir: 'ltr',
        icons: [
          {
            src: '/icons/icon-192.png',
            sizes: '192x192',
            type: 'image/png',
            purpose: 'any',
          },
          {
            src: '/icons/icon-512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'any',
          },
          {
            src: '/icons/icon-512-maskable.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable',
          },
        ],
      },
      workbox: {
        // Include .wasm so the Sleeve module is precached and works offline once installed.
        globPatterns: ['**/*.{js,css,html,ico,png,svg,woff2,wasm}'],
        // Don't cache the WS endpoint — we always want fresh blockchain data
        navigateFallbackDenylist: [/^\/api/],
        // Sleeve WASM is ~2 MB; raise the per-file precache cap so it doesn't get skipped silently.
        maximumFileSizeToCacheInBytes: 5 * 1024 * 1024,
      },
    }),
  ],
  resolve: {
    alias: {
      '@': '/src',
    },
  },
  server: {
    // Bind to all interfaces by default so on-device testing from a phone
    // on the same LAN works without remembering a --host flag every time.
    // Dev-mode only; production builds aren't served by Vite.
    //
    // WSL2 caveat: the Network URL Vite announces will likely be a
    // WSL-internal IP (10.x.x.x or 172.x.x.x) that your phone can't reach
    // because it's not on your LAN. To make the Network URL phone-
    // reachable, set up a port-proxy from the Windows host to WSL2:
    //
    //   # PowerShell as admin (one-time):
    //   netsh interface portproxy add v4tov4 \
    //     listenport=5173 listenaddress=0.0.0.0 \
    //     connectport=5173 connectaddress=$(wsl hostname -I | tr -d ' ')
    //
    // Then point your phone at http://<windows-LAN-IP>:5173/.
    // If that's too much hassle, fall back to Cloudflare deploy testing —
    // see env_wsl_cowork notes.
    host: true,
  },
  build: {
    target: 'es2020',
    // Production source maps are intentional: the repo is public OSS, so the
    // original source is already readable, and shipping maps aids debugging the
    // deployed PWA at negligible confidentiality cost. Switch to false or
    // 'hidden' if any private logic is ever bundled in.
    sourcemap: true,
    rollupOptions: {
      output: {
        // Rolldown (Vite 8's bundler) accepts only the function form of
        // manualChunks. Same split as the previous object form: the
        // polkadot API and crypto stacks get their own cacheable chunks.
        manualChunks(id: string) {
          if (id.includes('node_modules/@polkadot/api')) {
            return 'polkadot-api';
          }
          if (
            id.includes('node_modules/@polkadot/util-crypto') ||
            id.includes('node_modules/@polkadot/keyring') ||
            id.includes('node_modules/@polkadot/wasm-')
          ) {
            return 'polkadot-crypto';
          }
          return undefined;
        },
      },
    },
  },
  optimizeDeps: {
    // Polkadot packages need to be pre-bundled for dev speed
    include: [
      '@polkadot/api',
      '@polkadot/keyring',
      '@polkadot/util',
      '@polkadot/util-crypto',
    ],
  },
  test: {
    // Pure-function tests don't need a DOM. Keep node env for speed.
    environment: 'node',
    include: ['src/**/*.test.ts'],
    // Scrypt with N=131072 takes a few seconds in pure JS — give some headroom.
    testTimeout: 30000,
  },
});
